# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DEPPARSED(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tokens: str=None, parsetree: str=None):  # noqa: E501
        """DEPPARSED - a model defined in Swagger

        :param tokens: The tokens of this DEPPARSED.  # noqa: E501
        :type tokens: str
        :param parsetree: The parsetree of this DEPPARSED.  # noqa: E501
        :type parsetree: str
        """
        self.swagger_types = {
            'tokens': str,
            'parsetree': str
        }

        self.attribute_map = {
            'tokens': 'tokens',
            'parsetree': 'parsetree'
        }

        self._tokens = tokens
        self._parsetree = parsetree

    @classmethod
    def from_dict(cls, dikt) -> 'DEPPARSED':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DEPPARSED of this DEPPARSED.  # noqa: E501
        :rtype: DEPPARSED
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tokens(self) -> str:
        """Gets the tokens of this DEPPARSED.


        :return: The tokens of this DEPPARSED.
        :rtype: str
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens: str):
        """Sets the tokens of this DEPPARSED.


        :param tokens: The tokens of this DEPPARSED.
        :type tokens: str
        """
        if tokens is None:
            raise ValueError("Invalid value for `tokens`, must not be `None`")  # noqa: E501

        self._tokens = tokens

    @property
    def parsetree(self) -> str:
        """Gets the parsetree of this DEPPARSED.


        :return: The parsetree of this DEPPARSED.
        :rtype: str
        """
        return self._parsetree

    @parsetree.setter
    def parsetree(self, parsetree: str):
        """Sets the parsetree of this DEPPARSED.


        :param parsetree: The parsetree of this DEPPARSED.
        :type parsetree: str
        """
        if parsetree is None:
            raise ValueError("Invalid value for `parsetree`, must not be `None`")  # noqa: E501

        self._parsetree = parsetree
