# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ENTITY(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, tokens: str=None, entities: str=None):  # noqa: E501
        """ENTITY - a model defined in Swagger

        :param tokens: The tokens of this ENTITY.  # noqa: E501
        :type tokens: str
        :param entities: The entities of this ENTITY.  # noqa: E501
        :type entities: str
        """
        self.swagger_types = {
            'tokens': str,
            'entities': str
        }

        self.attribute_map = {
            'tokens': 'tokens',
            'entities': 'entities'
        }

        self._tokens = tokens
        self._entities = entities

    @classmethod
    def from_dict(cls, dikt) -> 'ENTITY':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ENTITY of this ENTITY.  # noqa: E501
        :rtype: ENTITY
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tokens(self) -> str:
        """Gets the tokens of this ENTITY.


        :return: The tokens of this ENTITY.
        :rtype: str
        """
        return self._tokens

    @tokens.setter
    def tokens(self, tokens: str):
        """Sets the tokens of this ENTITY.


        :param tokens: The tokens of this ENTITY.
        :type tokens: str
        """
        if tokens is None:
            raise ValueError("Invalid value for `tokens`, must not be `None`")  # noqa: E501

        self._tokens = tokens

    @property
    def entities(self) -> str:
        """Gets the entities of this ENTITY.


        :return: The entities of this ENTITY.
        :rtype: str
        """
        return self._entities

    @entities.setter
    def entities(self, entities: str):
        """Sets the entities of this ENTITY.


        :param entities: The entities of this ENTITY.
        :type entities: str
        """
        if entities is None:
            raise ValueError("Invalid value for `entities`, must not be `None`")  # noqa: E501

        self._entities = entities
