version: '3'

services:
  master:
    image: minchen57/hadoop-docker-python-sentiment-compose-master
    ports:
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
      - "50070:50070"
    container_name: "master"
    hostname: "master"
    domainname: "master"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:    
        constraints: [node.id == sssxd7rocpl67xyvm1979p67q]
    command: "/etc/startup.sh"

  worker:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker
    #container_name: "worker1"
    depends_on:
      - master
    deploy:
      mode: replicated
      replicas: 4






