version: '3'

services:
  master1:
    image: minchen57/hadoop-docker-python-sentiment-compose-master:latest
    ports:
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
      - "50070:50070"
      - "50075:50075"
      - "50010:50010"
    container_name: "master1"
    hostname: "master1"
    domainname: "master1"
    networks:
      - hadoop-sentiment
    command: ["/etc/bootstrap.sh", "-d"]

  worker:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker:latest
    #container_name: "worker1"
    depends_on:
      - master1
    networks:
      - hadoop-sentiment

networks:
  hadoop-sentiment:
    external:
      name: hadoop-sentiment


