version: '3'

services:
  master:
    image: minchen57/hadoop-docker-python-sentiment-compose-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    networks:
      - hadoop
    environment:
      - CLUSTER_NAME=test
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    #command: "/etc/startup.sh"

  worker1:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker
    ports:
      - "9901:9864"
      - "8041:8042"
    networks:
      - hadoop
    environment:
      SERVICE_PRECONDITION: "master:50070"
    deploy:
      # mode global will deploy one datanode per docker swarm node
      mode: global
      restart_policy:
        condition: on-failure


