swagger: '2.0'
info:
  version: 0.0.1
  title: postag
  description: >-
    A simple service to get some nlp features such as part of speech tagging,
    lemmatization, consituency parsing etc given an input string as a sentence
    using swagger -2.0 specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
host: 'localhost:8080'
basePath: /nlp
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/pos/{input}':
    get:
      parameters:
        - name: input
          in: path
          type: string
          description: Sentence to be tagged
          required: true
      responses:
        '200':
          description: Tagged sentences
          schema:
            $ref: '#/definitions/TAGGED'
  '/entity/{input}':
    get:
      parameters:
        - name: input
          in: path
          type: string
          description: Sentence to be parsed
          required: true
      responses:
        '200':
          description: Named Entities
          schema:
            $ref: '#/definitions/ENTITY'
  '/depparse/{input}':
    get:
      parameters:
        - name: input
          in: path
          type: string
          description: Sentence to be dependency-parsed
          required: true
      responses:
        '200':
          description: Dependency-Parsed sentences
          schema:
            $ref: '#/definitions/DEPPARSED'
  '/all/{input}':
    get:
      parameters:
        - name: input
          in: path
          type: string
          description: Sentence to be analyzed
          required: true
      responses:
        '200':
          description: All linguistic features
          schema:
            $ref: '#/definitions/ALLFEATURE'
            
definitions:
  TAGGED:
    type: object
    required:
      - tokens
      - tags
    properties:
      tokens:
        type: string
      tags:
        type: string
  ENTITY:
    type: object
    required:
      - tokens
      - entities
    properties:
      tokens:
        type: string
      entities:
        type: string
  DEPPARSED:
    type: object
    required:
      - tokens
      - parsetree
    properties:
      tokens:
        type: string
      parsetree:
        type: string
  ALLFEATURE:
    type: object
    required:
      - tokens
      - tags
      - parsetree
      - entities
    properties:
      tokens:
        type: string
      parsetree:
        type: string
      entities:
        type: string
      tags:
        type: string
