# coding: utf-8

# flake8: noqa

"""
    postag

    A simple service to get some nlp features such as part of speech tagging, lemmatization, consituency parsing etc given an input string as a sentence using swagger -2.0 specification and codegen  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.allfeature import ALLFEATURE
from swagger_client.models.depparsed import DEPPARSED
from swagger_client.models.entity import ENTITY
from swagger_client.models.tagged import TAGGED
