version: '3'

services:
  master:
    image: minchen57/hadoop-docker-python-sentiment-compose-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    command: "/etc/runall.sh"

  worker1:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker
    ports:
      - "9901:9864"
      - "8041:8042"

  worker2:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker
    ports:
      - "9902:9864"
      - "8042:8042"

