# coding: utf-8

"""
    postag

    A simple service to get some nlp features such as part of speech tagging, lemmatization, consituency parsing etc given an input string as a sentence using swagger -2.0 specification and codegen  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_all_input_get(self):
        """Test case for all_input_get

        """
        pass

    def test_depparse_input_get(self):
        """Test case for depparse_input_get

        """
        pass

    def test_entity_input_get(self):
        """Test case for entity_input_get

        """
        pass

    def test_pos_input_get(self):
        """Test case for pos_input_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
