# coding: utf-8

"""
    postag

    A simple service to get some nlp features such as part of speech tagging, lemmatization, consituency parsing etc given an input string as a sentence using swagger -2.0 specification and codegen  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.allfeature import ALLFEATURE  # noqa: E501
from swagger_client.rest import ApiException


class TestALLFEATURE(unittest.TestCase):
    """ALLFEATURE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testALLFEATURE(self):
        """Test ALLFEATURE"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.allfeature.ALLFEATURE()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
