version: '2'

services:
  master:
    image: minchen57/hadoop-docker-python-sentiment-compose-master:latest
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"

  worker1:
    image: minchen57/hadoop-docker-python-sentiment-compose-worker:latest
    container_name: "worker1"
    ports:
      - "9901:9864"
      - "8041:8042"

